In [1]:
#Exercise1
import numpy as np
import pandas as pd
array_1 = np.array(list(range(1, 11))).reshape(2, 5)
print(array_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
#Exercise2
array_2 = np.array(list(range(1, 21)))
extracted_elements = array_2[5:16]
print(array_2)
print(extracted_elements)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15 16]


In [13]:
#Exercise3
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruits['pears'] = 4
print(fruits)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [15]:
#Exercise4
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hank', 'Ivy', 'Jack'],
    'age': [25, 30, 22, 35, 40, 27, 29, 33, 31, 26],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'M']
}
df = pd.DataFrame(data)
print(df)

      name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    David   35      M
4      Eve   40      F
5    Frank   27      M
6    Grace   29      F
7     Hank   33      M
8      Ivy   31      F
9     Jack   26      M


In [17]:
#Exercise5
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print(df)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4      Eve   40      F     Manager
5    Frank   27      M     Analyst
6    Grace   29      F  Programmer
7     Hank   33      M     Manager
8      Ivy   31      F     Analyst
9     Jack   26      M  Programmer


In [19]:
#Exercise6
filtered_df=df[df['age']>=30]
print(filtered_df)

    name  age gender  occupation
1    Bob   30      M     Manager
3  David   35      M  Programmer
4    Eve   40      F     Manager
7   Hank   33      M     Manager
8    Ivy   31      F     Analyst


In [21]:
#Exercise7
df.to_csv('data.csv', index=False)
df_read = pd.read_csv('data.csv')
print(df_read)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4      Eve   40      F     Manager
5    Frank   27      M     Analyst
6    Grace   29      F  Programmer
7     Hank   33      M     Manager
8      Ivy   31      F     Analyst
9     Jack   26      M  Programmer
